import type { Item, Clinic, Report } from './types';

export const items: Item[] = [
  { id: 'wegovy', displayNameKo: '위고비', color: '#2E7D32' },
  { id: 'mounjaro', displayNameKo: '마운자로', color: '#1E88E5' },
];

export const clinics: Clinic[] = [
  {
    id: 'clinic-1',
    name: '강남웰빙의원',
    address: '서울특별시 강남구 테헤란로 123',
    location: { latitude: 37.508, longitude: 127.043 },
    mapPosition: { top: '45%', left: '55%' },
    geohash: 'wydm6',
    district: '서울 강남구',
    phone: '02-123-4567',
    website: 'https://example.com',
    status: { wegovy: 'available', mounjaro: 'unavailable' },
    price: { wegovy: 350000 },
    lastUpdated: new Date(Date.now() - 86400000 * 2).toISOString(),
    confidenceScore: 0.85,
  },
  {
    id: 'clinic-2',
    name: '분당튼튼병원',
    address: '경기도 성남시 분당구 판교역로 10',
    location: { latitude: 37.394, longitude: 127.111 },
    mapPosition: { top: '75%', left: '60%' },
    geohash: 'wydj7',
    district: '성남시 분당구',
    phone: '031-987-6543',
    website: 'https://example.com',
    status: { wegovy: 'unavailable', mounjaro: 'unavailable' },
    price: {},
    lastUpdated: new Date(Date.now() - 86400000 * 5).toISOString(),
    confidenceScore: 0.9,
  },
  {
    id: 'clinic-3',
    name: '동탄가정의학과',
    address: '경기도 화성시 동탄대로 500',
    location: { latitude: 37.203, longitude: 127.094 },
    mapPosition: { top: '88%', left: '58%' },
    geohash: 'wydh2',
    district: '동탄',
    phone: '031-111-2222',
    status: { wegovy: 'unknown', mounjaro: 'available' },
    price: { mounjaro: 420000 },
    lastUpdated: new Date(Date.now() - 86400000 * 1).toISOString(),
    confidenceScore: 0.7,
  },
  {
    id: 'clinic-4',
    name: '마포중앙의원',
    address: '서울특별시 마포구 월드컵북로 400',
    location: { latitude: 37.575, longitude: 126.898 },
    mapPosition: { top: '30%', left: '30%' },
    geohash: 'wydm2',
    district: '서울 마포구',
    status: { wegovy: 'available', mounjaro: 'available' },
    price: { wegovy: 380000, mounjaro: 400000 },
    lastUpdated: new Date(Date.now() - 86400000 * 10).toISOString(),
    confidenceScore: 0.5,
  },
    {
    id: 'clinic-5',
    name: '서초힐링클리닉',
    address: '서울특별시 서초구 서초대로 77',
    location: { latitude: 37.4979, longitude: 127.0276 },
    mapPosition: { top: '50%', left: '50%' },
    geohash: 'wydm6',
    district: '서울 서초구',
    phone: '02-555-7777',
    website: 'https://example.com',
    status: { wegovy: 'unavailable', mounjaro: 'available' },
    price: { mounjaro: 410000 },
    lastUpdated: new Date(Date.now() - 86400000 * 3).toISOString(),
    confidenceScore: 0.78,
  },
];

export const reports: Report[] = [
    {
        id: 'report-1',
        clinicId: 'clinic-1',
        clinicName: '강남웰빙의원',
        item: 'wegovy',
        availability: 'available',
        priceKRW: 350000,
        reportedBy: 'user-123',
        reportedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
        _date: new Date(Date.now() - 86400000 * 2),
        sourceType: 'phone',
        verification: 'community-verified',
        votes: 5,
        note: '전화로 확인했습니다. 재고 충분하다고 합니다.'
    },
    {
        id: 'report-2',
        clinicId: 'clinic-2',
        clinicName: '분당튼튼병원',
        item: 'mounjaro',
        availability: 'unavailable',
        reportedBy: 'user-456',
        reportedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
        _date: new Date(Date.now() - 86400000 * 5),
        sourceType: 'visit',
        verification: 'admin-verified',
        votes: 10,
        note: '직접 방문했는데 두 제품 모두 없다고 하네요.'
    },
    {
        id: 'report-3',
        clinicId: 'clinic-3',
        clinicName: '동탄가정의학과',
        item: 'mounjaro',
        availability: 'available',
        priceKRW: 420000,
        reportedBy: 'user-789',
        reportedAt: new Date().toISOString(),
        _date: new Date(),
        sourceType: 'kakao',
        verification: 'unverified',
        votes: 0,
        note: '카카오톡 상담으로 확인. 가격은 변동될 수 있다고 함.'
    }
]
