
import type { Item, Clinic, Report } from './types';

export const items: Item[] = [
  { id: 'wegovy', displayNameKo: '위고비', color: '#2E7D32' },
  { id: 'mounjaro', displayNameKo: '마운자로', color: '#1E88E5' },
];

export const clinics: Clinic[] = [
  {
    "id": "clinic-1",
    "name": "강남베스트의원",
    "address": "서울특별시 강남구 강남대로 390",
    "location": { "latitude": 37.4979, "longitude": 127.0276 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm6",
    "district": "서울 강남구",
    "phone": "02-111-1111",
    "status": { "wegovy": "available", "mounjaro": "unavailable" },
    "price": { "wegovy": 350000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 2).toISOString(),
    "confidenceScore": 0.9
  },
  {
    "id": "clinic-2",
    "name": "서초프라임클리닉",
    "address": "서울특별시 서초구 서초대로 248",
    "location": { "latitude": 37.4923, "longitude": 127.0143 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm3",
    "district": "서울 서초구",
    "phone": "02-222-2222",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 410000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 5).toISOString(),
    "confidenceScore": 0.85
  },
  {
    "id": "clinic-3",
    "name": "분당중앙가정의학과",
    "address": "경기도 성남시 분당구 성남대로 331번길 8",
    "location": { "latitude": 37.3826, "longitude": 127.1188 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj6",
    "district": "성남시 분당구",
    "phone": "031-333-3333",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 360000, "mounjaro": 400000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 1).toISOString(),
    "confidenceScore": 0.95
  },
  {
    "id": "clinic-4",
    "name": "동탄퍼스트내과",
    "address": "경기도 화성시 동탄중심상가2길 2",
    "location": { "latitude": 37.2046, "longitude": 127.0701 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydh8",
    "district": "동탄",
    "phone": "031-444-4444",
    "status": { "wegovy": "unknown", "mounjaro": "available" },
    "price": { "mounjaro": 420000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 8).toISOString(),
    "confidenceScore": 0.7
  },
  {
    "id": "clinic-5",
    "name": "송파스마일의원",
    "address": "서울특별시 송파구 올림픽로 212",
    "location": { "latitude": 37.5152, "longitude": 127.1023 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm7",
    "district": "서울 송파구",
    "phone": "02-555-5555",
    "status": { "wegovy": "available", "mounjaro": "unavailable" },
    "price": { "wegovy": 345000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 3).toISOString(),
    "confidenceScore": 0.8
  },
  {
    "id": "clinic-6",
    "name": "판교미래클리닉",
    "address": "경기도 성남시 분당구 대왕판교로 660",
    "location": { "latitude": 37.3948, "longitude": 127.1112 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj7",
    "district": "성남시 분당구",
    "phone": "031-666-6666",
    "status": { "wegovy": "unavailable", "mounjaro": "unavailable" },
    "price": {},
    "lastUpdated": new Date(Date.now() - 86400000 * 12).toISOString(),
    "confidenceScore": 0.9
  },
  {
    "id": "clinic-7",
    "name": "마포든든내과",
    "address": "서울특별시 마포구 월드컵북로 402",
    "location": { "latitude": 37.575, "longitude": 126.898 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm2",
    "district": "서울 마포구",
    "phone": "02-777-7777",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 370000, "mounjaro": 405000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 1).toISOString(),
    "confidenceScore": 0.98
  },
  {
    "id": "clinic-8",
    "name": "종로으뜸의원",
    "address": "서울특별시 종로구 종로 69",
    "location": { "latitude": 37.5704, "longitude": 126.9856 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm9",
    "district": "서울 종로구",
    "phone": "02-888-8888",
    "status": { "wegovy": "available", "mounjaro": "unknown" },
    "price": { "wegovy": 355000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 4).toISOString(),
    "confidenceScore": 0.75
  },
  {
    "id": "clinic-9",
    "name": "영등포희망클리닉",
    "address": "서울특별시 영등포구 경인로 841",
    "location": { "latitude": 37.5173, "longitude": 126.9083 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm0",
    "district": "서울 영등포구",
    "phone": "02-999-9999",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 415000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 6).toISOString(),
    "confidenceScore": 0.82
  },
  {
    "id": "clinic-10",
    "name": "동탄맘편한의원",
    "address": "경기도 화성시 동탄반석로 172",
    "location": { "latitude": 37.208, "longitude": 127.075 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydh9",
    "district": "동탄",
    "phone": "031-101-0101",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 365000, "mounjaro": 395000 },
    "lastUpdated": new Date().toISOString(),
    "confidenceScore": 1
  },
  {
    "id": "clinic-11",
    "name": "강동그린의원",
    "address": "서울특별시 강동구 천호대로 1089",
    "location": { "latitude": 37.5457, "longitude": 127.1364 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydrq",
    "district": "서울 강동구",
    "phone": "02-112-2334",
    "status": { "wegovy": "available", "mounjaro": "unavailable" },
    "price": { "wegovy": 340000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 7).toISOString(),
    "confidenceScore": 0.78
  },
  {
    "id": "clinic-12",
    "name": "정자역패밀리의원",
    "address": "경기도 성남시 분당구 정자일로 197",
    "location": { "latitude": 37.369, "longitude": 127.107 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj6",
    "district": "성남시 분당구",
    "phone": "031-321-4321",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 405000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 3).toISOString(),
    "confidenceScore": 0.88
  },
  {
    "id": "clinic-13",
    "name": "용산서울클리닉",
    "address": "서울특별시 용산구 한강대로 23길 55",
    "location": { "latitude": 37.5298, "longitude": 126.964 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm6",
    "district": "서울 용산구",
    "phone": "02-797-0000",
    "status": { "wegovy": "unknown", "mounjaro": "unknown" },
    "price": {},
    "lastUpdated": new Date(Date.now() - 86400000 * 20).toISOString(),
    "confidenceScore": 0.5
  },
  {
    "id": "clinic-14",
    "name": "성북연세내과",
    "address": "서울특별시 성북구 동소문로 22",
    "location": { "latitude": 37.5891, "longitude": 127.0182 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydmc",
    "district": "서울 성북구",
    "phone": "02-921-5566",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 375000, "mounjaro": 415000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 1).toISOString(),
    "confidenceScore": 0.92
  },
  {
    "id": "clinic-15",
    "name": "동탄호수공원의원",
    "address": "경기도 화성시 동탄대로5길 21",
    "location": { "latitude": 37.185, "longitude": 127.080 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydh2",
    "district": "동탄",
    "phone": "031-159-7531",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 425000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 4).toISOString(),
    "confidenceScore": 0.8
  },
  {
    "id": "clinic-16",
    "name": "관악이편한내과",
    "address": "서울특별시 관악구 관악로 164",
    "location": { "latitude": 37.478, "longitude": 126.951 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydk5",
    "district": "서울 관악구",
    "phone": "02-882-1234",
    "status": { "wegovy": "available", "mounjaro": "unavailable" },
    "price": { "wegovy": 330000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 9).toISOString(),
    "confidenceScore": 0.7
  },
  {
    "id": "clinic-17",
    "name": "미금역봄날의원",
    "address": "경기도 성남시 분당구 돌마로 46",
    "location": { "latitude": 37.349, "longitude": 127.108 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj3",
    "district": "성남시 분당구",
    "phone": "031-717-8275",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 355000, "mounjaro": 390000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 2).toISOString(),
    "confidenceScore": 0.91
  },
  {
    "id": "clinic-18",
    "name": "강서연합의원",
    "address": "서울특별시 강서구 화곡로 302",
    "location": { "latitude": 37.560, "longitude": 126.840 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydmb",
    "district": "서울 강서구",
    "phone": "02-269-1111",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 430000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 5).toISOString(),
    "confidenceScore": 0.83
  },
  {
    "id": "clinic-19",
    "name": "노원코끼리의원",
    "address": "서울특별시 노원구 동일로 1414",
    "location": { "latitude": 37.656, "longitude": 127.062 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydrs",
    "district": "서울 노원구",
    "phone": "02-930-7777",
    "status": { "wegovy": "available", "mounjaro": "unknown" },
    "price": { "wegovy": 380000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 15).toISOString(),
    "confidenceScore": 0.65
  },
  {
    "id": "clinic-20",
    "name": "서현역퍼스트클리닉",
    "address": "경기도 성남시 분당구 황새울로360번길 21",
    "location": { "latitude": 37.385, "longitude": 127.123 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj6",
    "district": "성남시 분당구",
    "phone": "031-801-7770",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 360000, "mounjaro": 400000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 3).toISOString(),
    "confidenceScore": 0.89
  },
  {
    "id": "clinic-21",
    "name": "광진하나의원",
    "address": "서울특별시 광진구 아차산로 272",
    "location": { "latitude": 37.539, "longitude": 127.072 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm7",
    "district": "서울 광진구",
    "phone": "02-456-1004",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 410000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 6).toISOString(),
    "confidenceScore": 0.8
  },
  {
    "id": "clinic-22",
    "name": "동탄센트럴파크의원",
    "address": "경기도 화성시 동탄공원로2길 25",
    "location": { "latitude": 37.215, "longitude": 127.072 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydh9",
    "district": "동탄",
    "phone": "031-222-3333",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 370000, "mounjaro": 400000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 1).toISOString(),
    "confidenceScore": 0.95
  },
  {
    "id": "clinic-23",
    "name": "구로디지털엔젤의원",
    "address": "서울특별시 구로구 디지털로 306",
    "location": { "latitude": 37.485, "longitude": 126.901 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydk4",
    "district": "서울 구로구",
    "phone": "02-861-8888",
    "status": { "wegovy": "available", "mounjaro": "unavailable" },
    "price": { "wegovy": 345000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 4).toISOString(),
    "confidenceScore": 0.82
  },
  {
    "id": "clinic-24",
    "name": "수내역푸른내과",
    "address": "경기도 성남시 분당구 백현로101번길 20",
    "location": { "latitude": 37.377, "longitude": 127.114 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj6",
    "district": "성남시 분당구",
    "phone": "031-711-9999",
    "status": { "wegovy": "unknown", "mounjaro": "available" },
    "price": { "mounjaro": 395000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 10).toISOString(),
    "confidenceScore": 0.72
  },
  {
    "id": "clinic-25",
    "name": "은평새로운의원",
    "address": "서울특별시 은평구 은평로 196",
    "location": { "latitude": 37.603, "longitude": 126.918 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm8",
    "district": "서울 은평구",
    "phone": "02-353-5000",
    "status": { "wegovy": "unavailable", "mounjaro": "unavailable" },
    "price": {},
    "lastUpdated": new Date(Date.now() - 86400000 * 18).toISOString(),
    "confidenceScore": 0.88
  },
  {
    "id": "clinic-26",
    "name": "강북삼성가정의학과",
    "address": "서울특별시 강북구 도봉로 328",
    "location": { "latitude": 37.639, "longitude": 127.026 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydmd",
    "district": "서울 강북구",
    "phone": "02-985-1234",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 385000, "mounjaro": 425000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 3).toISOString(),
    "confidenceScore": 0.85
  },
  {
    "id": "clinic-27",
    "name": "동탄역클리닉",
    "address": "경기도 화성시 동탄역로 151",
    "location": { "latitude": 37.201, "longitude": 127.099 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydh8",
    "district": "동탄",
    "phone": "031-375-8282",
    "status": { "wegovy": "available", "mounjaro": "unavailable" },
    "price": { "wegovy": 360000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 5).toISOString(),
    "confidenceScore": 0.79
  },
  {
    "id": "clinic-28",
    "name": "야탑서울내과",
    "address": "경기도 성남시 분당구 야탑로69번길 24",
    "location": { "latitude": 37.411, "longitude": 127.128 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydjk",
    "district": "성남시 분당구",
    "phone": "031-701-8888",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 410000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 2).toISOString(),
    "confidenceScore": 0.9
  },
  {
    "id": "clinic-29",
    "name": "중구성심의원",
    "address": "서울특별시 중구 을지로 39",
    "location": { "latitude": 37.566, "longitude": 126.982 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm9",
    "district": "서울 중구",
    "phone": "02-226-7777",
    "status": { "wegovy": "available", "mounjaro": "unknown" },
    "price": { "wegovy": 350000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 7).toISOString(),
    "confidenceScore": 0.76
  },
  {
    "id": "clinic-30",
    "name": "동대문속편한내과",
    "address": "서울특별시 동대문구 왕산로 214",
    "location": { "latitude": 37.574, "longitude": 127.041 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydmf",
    "district": "서울 동대문구",
    "phone": "02-221-1234",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 365000, "mounjaro": 405000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 1).toISOString(),
    "confidenceScore": 0.94
  },
  {
    "id": "clinic-31",
    "name": "강남세브란스의원",
    "address": "서울특별시 강남구 도곡로 235",
    "location": { "latitude": 37.493, "longitude": 127.048 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm6",
    "district": "서울 강남구",
    "phone": "02-2019-3114",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 400000, "mounjaro": 450000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 14).toISOString(),
    "confidenceScore": 0.68
  },
  {
    "id": "clinic-32",
    "name": "오리역참좋은의원",
    "address": "경기도 성남시 분당구 성남대로 34",
    "location": { "latitude": 37.338, "longitude": 127.108 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj1",
    "district": "성남시 분당구",
    "phone": "031-715-1234",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 400000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 3).toISOString(),
    "confidenceScore": 0.87
  },
  {
    "id": "clinic-33",
    "name": "동탄위드유의원",
    "address": "경기도 화성시 동탄솔빛로 56",
    "location": { "latitude": 37.223, "longitude": 127.068 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydh9",
    "district": "동탄",
    "phone": "031-373-1111",
    "status": { "wegovy": "available", "mounjaro": "unavailable" },
    "price": { "wegovy": 375000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 8).toISOString(),
    "confidenceScore": 0.74
  },
  {
    "id": "clinic-34",
    "name": "잠실주치의의원",
    "address": "서울특별시 송파구 석촌호수로 220",
    "location": { "latitude": 37.509, "longitude": 127.106 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm7",
    "district": "서울 송파구",
    "phone": "02-414-8275",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 355000, "mounjaro": 410000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 2).toISOString(),
    "confidenceScore": 0.93
  },
  {
    "id": "clinic-35",
    "name": "동작삼성내과",
    "address": "서울특별시 동작구 상도로 369",
    "location": { "latitude": 37.503, "longitude": 126.944 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydk5",
    "district": "서울 동작구",
    "phone": "02-812-7575",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 420000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 5).toISOString(),
    "confidenceScore": 0.81
  },
  {
    "id": "clinic-36",
    "name": "성수연세가정의원",
    "address": "서울특별시 성동구 아차산로7길 15-1",
    "location": { "latitude": 37.543, "longitude": 127.054 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydmf",
    "district": "서울 성동구",
    "phone": "02-461-8275",
    "status": { "wegovy": "available", "mounjaro": "unavailable" },
    "price": { "wegovy": 360000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 11).toISOString(),
    "confidenceScore": 0.71
  },
  {
    "id": "clinic-37",
    "name": "이매촌가정의학과",
    "address": "경기도 성남시 분당구 이매로 40",
    "location": { "latitude": 37.397, "longitude": 127.133 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydjj",
    "district": "성남시 분당구",
    "phone": "031-705-1111",
    "status": { "wegovy": "unknown", "mounjaro": "available" },
    "price": { "mounjaro": 398000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 4).toISOString(),
    "confidenceScore": 0.84
  },
  {
    "id": "clinic-38",
    "name": "양천연세365의원",
    "address": "서울특별시 양천구 목동동로 293",
    "location": { "latitude": 37.527, "longitude": 126.875 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydk7",
    "district": "서울 양천구",
    "phone": "02-265-3650",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 370000, "mounjaro": 410000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 1).toISOString(),
    "confidenceScore": 0.96
  },
  {
    "id": "clinic-39",
    "name": "수지미래산부인과",
    "address": "경기도 용인시 수지구 풍덕천로 149",
    "location": { "latitude": 37.322, "longitude": 127.095 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj0",
    "district": "성남시 분당구",
    "phone": "031-262-1000",
    "status": { "wegovy": "unavailable", "mounjaro": "unavailable" },
    "price": {},
    "lastUpdated": new Date(Date.now() - 86400000 * 25).toISOString(),
    "confidenceScore": 0.8
  },
  {
    "id": "clinic-40",
    "name": "동탄푸른소아청소년과",
    "address": "경기도 화성시 동탄대로시범길 148-14",
    "location": { "latitude": 37.198, "longitude": 127.105 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydh8",
    "district": "동탄",
    "phone": "031-374-1234",
    "status": { "wegovy": "available", "mounjaro": "unknown" },
    "price": { "wegovy": 380000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 6).toISOString(),
    "confidenceScore": 0.77
  },
  {
    "id": "clinic-41",
    "name": "홍대스타일의원",
    "address": "서울특별시 마포구 양화로 165",
    "location": { "latitude": 37.556, "longitude": 126.922 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm8",
    "district": "서울 마포구",
    "phone": "02-332-8888",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 360000, "mounjaro": 400000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 2).toISOString(),
    "confidenceScore": 0.92
  },
  {
    "id": "clinic-42",
    "name": "서초아이사랑소아과",
    "address": "서울특별시 서초구 신반포로 176",
    "location": { "latitude": 37.505, "longitude": 127.005 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydm6",
    "district": "서울 서초구",
    "phone": "02-532-1000",
    "status": { "wegovy": "unavailable", "mounjaro": "unavailable" },
    "price": {},
    "lastUpdated": new Date(Date.now() - 86400000 * 30).toISOString(),
    "confidenceScore": 0.75
  },
  {
    "id": "clinic-43",
    "name": "분당제생병원 가정의학과",
    "address": "경기도 성남시 분당구 서현로180번길 20",
    "location": { "latitude": 37.387, "longitude": 127.127 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj6",
    "district": "성남시 분당구",
    "phone": "031-779-5000",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 390000, "mounjaro": 430000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 9).toISOString(),
    "confidenceScore": 0.73
  },
  {
    "id": "clinic-44",
    "name": "광교중앙클리닉",
    "address": "경기도 수원시 영통구 광교중앙로 145",
    "location": { "latitude": 37.289, "longitude": 127.05 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj2",
    "district": "동탄",
    "phone": "031-211-7575",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 415000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 4).toISOString(),
    "confidenceScore": 0.83
  },
  {
    "id": "clinic-45",
    "name": "성북우리의원",
    "address": "서울특별시 성북구 보문로 168",
    "location": { "latitude": 37.585, "longitude": 127.019 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydmc",
    "district": "서울 성북구",
    "phone": "02-925-1111",
    "status": { "wegovy": "available", "mounjaro": "unavailable" },
    "price": { "wegovy": 370000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 6).toISOString(),
    "confidenceScore": 0.78
  },
  {
    "id": "clinic-46",
    "name": "천호로데오의원",
    "address": "서울특별시 강동구 천호대로157길 46",
    "location": { "latitude": 37.538, "longitude": 127.125 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydrq",
    "district": "서울 강동구",
    "phone": "02-475-9999",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 360000, "mounjaro": 400000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 1).toISOString(),
    "confidenceScore": 0.97
  },
  {
    "id": "clinic-47",
    "name": "서울대입구역내과",
    "address": "서울특별시 관악구 남부순환로 1827",
    "location": { "latitude": 37.481, "longitude": 126.953 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydk5",
    "district": "서울 관악구",
    "phone": "02-878-5555",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 410000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 3).toISOString(),
    "confidenceScore": 0.86
  },
  {
    "id": "clinic-48",
    "name": "이수역메디컬의원",
    "address": "서울특별시 동작구 동작대로 115",
    "location": { "latitude": 37.485, "longitude": 126.982 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydk7",
    "district": "서울 동작구",
    "phone": "02-581-2222",
    "status": { "wegovy": "available", "mounjaro": "unknown" },
    "price": { "wegovy": 350000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 13).toISOString(),
    "confidenceScore": 0.69
  },
  {
    "id": "clinic-49",
    "name": "판교테크노밸리의원",
    "address": "경기도 성남시 분당구 판교로 255",
    "location": { "latitude": 37.401, "longitude": 127.106 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydj7",
    "district": "성남시 분당구",
    "phone": "031-628-1000",
    "status": { "wegovy": "available", "mounjaro": "available" },
    "price": { "wegovy": 380000, "mounjaro": 420000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 5).toISOString(),
    "confidenceScore": 0.84
  },
  {
    "id": "clinic-50",
    "name": "여의도국제의원",
    "address": "서울특별시 영등포구 국제금융로 10",
    "location": { "latitude": 37.525, "longitude": 126.924 },
    "mapPosition": { "top": "0", "left": "0" },
    "geohash": "wydk6",
    "district": "서울 영등포구",
    "phone": "02-782-1234",
    "status": { "wegovy": "unavailable", "mounjaro": "available" },
    "price": { "mounjaro": 440000 },
    "lastUpdated": new Date(Date.now() - 86400000 * 2).toISOString(),
    "confidenceScore": 0.9
  }
];


export const reports: Report[] = [
    {
        id: 'report-1',
        clinicId: 'clinic-1',
        clinicName: '강남베스트의원',
        item: 'wegovy',
        availability: 'available',
        priceKRW: 350000,
        reportedBy: 'user-abc',
        reportedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
        _date: new Date(Date.now() - 86400000 * 2),
        sourceType: 'phone',
        verification: 'community-verified',
        votes: 8,
        note: '2주치 재고 확인했습니다.'
    },
    {
        id: 'report-2',
        clinicId: 'clinic-3',
        clinicName: '분당중앙가정의학과',
        item: 'mounjaro',
        availability: 'available',
        priceKRW: 400000,
        reportedBy: 'user-def',
        reportedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
        _date: new Date(Date.now() - 86400000 * 1),
        sourceType: 'visit',
        verification: 'admin-verified',
        votes: 15,
        note: '오늘 방문해서 처방받았어요. 위고비도 있다고 합니다.'
    },
    {
        id: 'report-3',
        clinicId: 'clinic-4',
        clinicName: '동탄퍼스트내과',
        item: 'mounjaro',
        availability: 'available',
        priceKRW: 420000,
        reportedBy: 'user-ghi',
        reportedAt: new Date().toISOString(),
        _date: new Date(),
        sourceType: 'kakao',
        verification: 'unverified',
        votes: 2,
        note: '카톡으로 문의했고, 재고 소량 있다고 답변 받았습니다.'
    },
    {
        id: 'report-4',
        clinicId: 'clinic-6',
        clinicName: '판교미래클리닉',
        item: 'wegovy',
        availability: 'unavailable',
        reportedBy: 'user-jkl',
        reportedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
        _date: new Date(Date.now() - 86400000 * 12),
        sourceType: 'phone',
        verification: 'community-verified',
        votes: 6,
        note: '전화해봤는데 두 약 모두 현재 품절이고, 재입고 예정 없다고 합니다.'
    }
]

    

    